bill = input("Welcome to the tip calculator!\nWhat was the total bill? $")
tip = input("What percentage tip would you like to give? 10, 12, or 15? ")
people = input("How many people to split the bill? ")
total_bill = float(bill) * (1 + int(tip) / 100)
split_bill = total_bill / int(people)
print(f"Each person should pay: ${round(split_bill, 2)}")
